package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/JameelGharra/ascii-craft/server/encoder"
	"github.com/JameelGharra/ascii-craft/server/encoding/huffman"
)

func main() {
	outPath := filepath.Join("..", "frontend", "src", "protocol_constants.ts")

	file, err := os.Create(outPath)
	if err != nil {
		panic(err)
	}
	defer file.Close()

	fmt.Fprintln(file, "// AUTO-GENERATED BY GO. DO NOT EDIT MANUALLY.")
	fmt.Fprintf(file, "export const FLAG_IS_COMPRESSED = %d;\n", encoder.FlagIsCompressed)
	fmt.Fprintf(file, "export const FLAG_METHOD = %d;\n", encoder.FlagMethod)
	fmt.Fprintf(file, "export const FLAG_IS_DELTA = %d;\n", encoder.FlagIsDelta)
	fmt.Fprintln(file)

	fmt.Fprintln(file, "export const MASK_TABLE_MODE = 0x18; // Bits 3 and 4")
	fmt.Fprintln(file, "export const SHIFT_TABLE_MODE = 3;")
	fmt.Fprintln(file)

	fmt.Fprintf(file, "export const TABLE_MODE_RAW = %d;\n", huffman.TableModeRaw)
	fmt.Fprintf(file, "export const TABLE_MODE_RLE = %d;\n", huffman.TableModeRLE)
	fmt.Fprintf(file, "export const TABLE_MODE_SPARSE = %d;\n", huffman.TableModeSparse)

	fmt.Printf("Successfully generated %s\n", outPath)
}
