// AUTO-GENERATED BY GO. DO NOT EDIT MANUALLY.
export const FLAG_IS_COMPRESSED = 1;
export const FLAG_METHOD = 2;
export const FLAG_IS_DELTA = 4;

export const MASK_TABLE_MODE = 0x18; // Bits 3 and 4
export const SHIFT_TABLE_MODE = 3;

export const TABLE_MODE_RAW = 0;
export const TABLE_MODE_RLE = 1;
export const TABLE_MODE_SPARSE = 2;
